/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package interfazUsuario;

import javax.swing.JPanel;

/**
 *
 * @author joser
 */
public class FrmAbarrotes extends javax.swing.JFrame {

    /**
     * Creates new form FrmAbarrotes
     */
    public FrmAbarrotes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        AgregarProductoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        ConsultarProductoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ActualizarProductoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EliminarProductoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        MovimientosCompraPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MovimientosVentaPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        AgregarInventarioPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        EliminarInventarioPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ActualizarInventarioPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ListadoCompletoPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ListadoClavePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ListadoTipoPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        InventarioTodosPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        InventarioProductosGranelPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        InventarioRegistroVentasPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        InventarioRegistroComprasPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        RegistroVentasPeriodoPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        RegistroComprasPeriodoPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        CatalogosMenu = new javax.swing.JMenu();
        ProductosGranelMenu = new javax.swing.JMenu();
        AgregarProductoGranel = new javax.swing.JMenuItem();
        ConsultarProductoGranel = new javax.swing.JMenuItem();
        ActualizarProductoGranel = new javax.swing.JMenuItem();
        EliminarProductoGranel = new javax.swing.JMenuItem();
        MovimientosMenu = new javax.swing.JMenu();
        MovimientosCompra = new javax.swing.JMenuItem();
        MovimientosVenta = new javax.swing.JMenuItem();
        MovimientosInventarioMenu = new javax.swing.JMenu();
        AgregarInventario = new javax.swing.JMenuItem();
        EliminarInventario = new javax.swing.JMenuItem();
        ActualizarInventario = new javax.swing.JMenuItem();
        ConsultasMenu = new javax.swing.JMenu();
        ConsultasProductoMenu = new javax.swing.JMenu();
        ProductoListadoCompleto = new javax.swing.JMenuItem();
        ProductoListadoClave = new javax.swing.JMenuItem();
        ProductoListadoTipo = new javax.swing.JMenuItem();
        ConsultasInventarioMenu = new javax.swing.JMenu();
        InventarioTodos = new javax.swing.JMenuItem();
        InventarioProductosGranel = new javax.swing.JMenuItem();
        InventarioRegistroVentas = new javax.swing.JMenuItem();
        InventarioRegistroCompras = new javax.swing.JMenuItem();
        InventarioVentasPeriodo = new javax.swing.JMenuItem();
        InventarioComprasPeriodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Agregar Producto");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("Nombre:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setText("Unidad de medida:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setText("Tipo:");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField2.setText("Nombre");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField3.setText("jTextField2");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField4.setText("jTextField2");

        javax.swing.GroupLayout AgregarProductoPanelLayout = new javax.swing.GroupLayout(AgregarProductoPanel);
        AgregarProductoPanel.setLayout(AgregarProductoPanelLayout);
        AgregarProductoPanelLayout.setHorizontalGroup(
            AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarProductoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarProductoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGap(66, 66, 66))
        );
        AgregarProductoPanelLayout.setVerticalGroup(
            AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Consultar Producto");

        javax.swing.GroupLayout ConsultarProductoPanelLayout = new javax.swing.GroupLayout(ConsultarProductoPanel);
        ConsultarProductoPanel.setLayout(ConsultarProductoPanelLayout);
        ConsultarProductoPanelLayout.setHorizontalGroup(
            ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        ConsultarProductoPanelLayout.setVerticalGroup(
            ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Actualizar Producto");

        javax.swing.GroupLayout ActualizarProductoPanelLayout = new javax.swing.GroupLayout(ActualizarProductoPanel);
        ActualizarProductoPanel.setLayout(ActualizarProductoPanelLayout);
        ActualizarProductoPanelLayout.setHorizontalGroup(
            ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        ActualizarProductoPanelLayout.setVerticalGroup(
            ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("Eliminar Producto");

        javax.swing.GroupLayout EliminarProductoPanelLayout = new javax.swing.GroupLayout(EliminarProductoPanel);
        EliminarProductoPanel.setLayout(EliminarProductoPanelLayout);
        EliminarProductoPanelLayout.setHorizontalGroup(
            EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        EliminarProductoPanelLayout.setVerticalGroup(
            EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("Movimientos de compras");

        javax.swing.GroupLayout MovimientosCompraPanelLayout = new javax.swing.GroupLayout(MovimientosCompraPanel);
        MovimientosCompraPanel.setLayout(MovimientosCompraPanelLayout);
        MovimientosCompraPanelLayout.setHorizontalGroup(
            MovimientosCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientosCompraPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        MovimientosCompraPanelLayout.setVerticalGroup(
            MovimientosCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientosCompraPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setText("Movimientos de ventas");

        javax.swing.GroupLayout MovimientosVentaPanelLayout = new javax.swing.GroupLayout(MovimientosVentaPanel);
        MovimientosVentaPanel.setLayout(MovimientosVentaPanelLayout);
        MovimientosVentaPanelLayout.setHorizontalGroup(
            MovimientosVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientosVentaPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        MovimientosVentaPanelLayout.setVerticalGroup(
            MovimientosVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientosVentaPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setText("Agregar movimiento");

        javax.swing.GroupLayout AgregarInventarioPanelLayout = new javax.swing.GroupLayout(AgregarInventarioPanel);
        AgregarInventarioPanel.setLayout(AgregarInventarioPanelLayout);
        AgregarInventarioPanelLayout.setHorizontalGroup(
            AgregarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInventarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        AgregarInventarioPanelLayout.setVerticalGroup(
            AgregarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setText("Eliminar movimiento");

        javax.swing.GroupLayout EliminarInventarioPanelLayout = new javax.swing.GroupLayout(EliminarInventarioPanel);
        EliminarInventarioPanel.setLayout(EliminarInventarioPanelLayout);
        EliminarInventarioPanelLayout.setHorizontalGroup(
            EliminarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarInventarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        EliminarInventarioPanelLayout.setVerticalGroup(
            EliminarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setText("Actualizar movimiento");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout ActualizarInventarioPanelLayout = new javax.swing.GroupLayout(ActualizarInventarioPanel);
        ActualizarInventarioPanel.setLayout(ActualizarInventarioPanelLayout);
        ActualizarInventarioPanelLayout.setHorizontalGroup(
            ActualizarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                .addGroup(ActualizarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        ActualizarInventarioPanelLayout.setVerticalGroup(
            ActualizarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(114, 114, 114)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setText("Listado completo de productos");

        javax.swing.GroupLayout ListadoCompletoPanelLayout = new javax.swing.GroupLayout(ListadoCompletoPanel);
        ListadoCompletoPanel.setLayout(ListadoCompletoPanelLayout);
        ListadoCompletoPanelLayout.setHorizontalGroup(
            ListadoCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        ListadoCompletoPanelLayout.setVerticalGroup(
            ListadoCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel11.setText("Listado completo por clave");

        javax.swing.GroupLayout ListadoClavePanelLayout = new javax.swing.GroupLayout(ListadoClavePanel);
        ListadoClavePanel.setLayout(ListadoClavePanelLayout);
        ListadoClavePanelLayout.setHorizontalGroup(
            ListadoClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoClavePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        ListadoClavePanelLayout.setVerticalGroup(
            ListadoClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoClavePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setText("Listado completo por tipo");

        javax.swing.GroupLayout ListadoTipoPanelLayout = new javax.swing.GroupLayout(ListadoTipoPanel);
        ListadoTipoPanel.setLayout(ListadoTipoPanelLayout);
        ListadoTipoPanelLayout.setHorizontalGroup(
            ListadoTipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoTipoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        ListadoTipoPanelLayout.setVerticalGroup(
            ListadoTipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoTipoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setText("Inventario");

        javax.swing.GroupLayout InventarioTodosPanelLayout = new javax.swing.GroupLayout(InventarioTodosPanel);
        InventarioTodosPanel.setLayout(InventarioTodosPanelLayout);
        InventarioTodosPanelLayout.setHorizontalGroup(
            InventarioTodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioTodosPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioTodosPanelLayout.setVerticalGroup(
            InventarioTodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioTodosPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setText("Inventario productos Granel");

        javax.swing.GroupLayout InventarioProductosGranelPanelLayout = new javax.swing.GroupLayout(InventarioProductosGranelPanel);
        InventarioProductosGranelPanel.setLayout(InventarioProductosGranelPanelLayout);
        InventarioProductosGranelPanelLayout.setHorizontalGroup(
            InventarioProductosGranelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioProductosGranelPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioProductosGranelPanelLayout.setVerticalGroup(
            InventarioProductosGranelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioProductosGranelPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setText("Registro de ventas");

        javax.swing.GroupLayout InventarioRegistroVentasPanelLayout = new javax.swing.GroupLayout(InventarioRegistroVentasPanel);
        InventarioRegistroVentasPanel.setLayout(InventarioRegistroVentasPanelLayout);
        InventarioRegistroVentasPanelLayout.setHorizontalGroup(
            InventarioRegistroVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroVentasPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioRegistroVentasPanelLayout.setVerticalGroup(
            InventarioRegistroVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroVentasPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel19.setText("Registro de compras");

        javax.swing.GroupLayout InventarioRegistroComprasPanelLayout = new javax.swing.GroupLayout(InventarioRegistroComprasPanel);
        InventarioRegistroComprasPanel.setLayout(InventarioRegistroComprasPanelLayout);
        InventarioRegistroComprasPanelLayout.setHorizontalGroup(
            InventarioRegistroComprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroComprasPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioRegistroComprasPanelLayout.setVerticalGroup(
            InventarioRegistroComprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroComprasPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setText("Registro de ventas por periodo");

        javax.swing.GroupLayout RegistroVentasPeriodoPanelLayout = new javax.swing.GroupLayout(RegistroVentasPeriodoPanel);
        RegistroVentasPeriodoPanel.setLayout(RegistroVentasPeriodoPanelLayout);
        RegistroVentasPeriodoPanelLayout.setHorizontalGroup(
            RegistroVentasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroVentasPeriodoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        RegistroVentasPeriodoPanelLayout.setVerticalGroup(
            RegistroVentasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroVentasPeriodoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setText("Registro de compras por periodo");

        javax.swing.GroupLayout RegistroComprasPeriodoPanelLayout = new javax.swing.GroupLayout(RegistroComprasPeriodoPanel);
        RegistroComprasPeriodoPanel.setLayout(RegistroComprasPeriodoPanelLayout);
        RegistroComprasPeriodoPanelLayout.setHorizontalGroup(
            RegistroComprasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroComprasPeriodoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        RegistroComprasPeriodoPanelLayout.setVerticalGroup(
            RegistroComprasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroComprasPeriodoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel18)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MovimientosVentaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioProductosGranelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroVentasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroComprasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistroComprasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioTodosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoTipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoClavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoCompletoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MovimientosCompraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultarProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(RegistroVentasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MovimientosVentaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioProductosGranelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroVentasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroComprasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistroComprasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioTodosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoTipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoClavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoCompletoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MovimientosCompraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultarProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(RegistroVentasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        CatalogosMenu.setMnemonic('c');
        CatalogosMenu.setText("Catalogos");

        ProductosGranelMenu.setText("Productos Granel");

        AgregarProductoGranel.setText("Agregar");
        AgregarProductoGranel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AgregarProductoGranelComponentAdded(evt);
            }
        });
        AgregarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(AgregarProductoGranel);

        ConsultarProductoGranel.setText("Consultar");
        ConsultarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(ConsultarProductoGranel);

        ActualizarProductoGranel.setText("Actualizar");
        ActualizarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(ActualizarProductoGranel);

        EliminarProductoGranel.setText("Eliminar");
        EliminarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(EliminarProductoGranel);

        CatalogosMenu.add(ProductosGranelMenu);

        menuBar.add(CatalogosMenu);

        MovimientosMenu.setMnemonic('m');
        MovimientosMenu.setText("Movimientos");

        MovimientosCompra.setText("Compra");
        MovimientosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosCompraActionPerformed(evt);
            }
        });
        MovimientosMenu.add(MovimientosCompra);

        MovimientosVenta.setText("Venta");
        MovimientosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosVentaActionPerformed(evt);
            }
        });
        MovimientosMenu.add(MovimientosVenta);

        MovimientosInventarioMenu.setText("Inventario");

        AgregarInventario.setText("Agregar");
        AgregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(AgregarInventario);

        EliminarInventario.setText("Eliminar");
        EliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(EliminarInventario);

        ActualizarInventario.setText("Actualizar");
        ActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(ActualizarInventario);

        MovimientosMenu.add(MovimientosInventarioMenu);

        menuBar.add(MovimientosMenu);

        ConsultasMenu.setMnemonic('x');
        ConsultasMenu.setText("Consultas");

        ConsultasProductoMenu.setText("Producto");

        ProductoListadoCompleto.setText("Listado completo");
        ProductoListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoCompletoActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoCompleto);

        ProductoListadoClave.setText("Listado por clave");
        ProductoListadoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoClaveActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoClave);

        ProductoListadoTipo.setText("Listado por tipo");
        ProductoListadoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoTipoActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoTipo);

        ConsultasMenu.add(ConsultasProductoMenu);

        ConsultasInventarioMenu.setText("Inventario");

        InventarioTodos.setText("Todos los productos");
        InventarioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioTodosActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioTodos);

        InventarioProductosGranel.setText("Productos Granel");
        InventarioProductosGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioProductosGranelActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioProductosGranel);

        InventarioRegistroVentas.setText("Registro de ventas");
        InventarioRegistroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioRegistroVentasActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioRegistroVentas);

        InventarioRegistroCompras.setText("Registro de compras");
        InventarioRegistroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioRegistroComprasActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioRegistroCompras);

        InventarioVentasPeriodo.setText("Ventas dentro de un periodo");
        InventarioVentasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioVentasPeriodoActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioVentasPeriodo);

        InventarioComprasPeriodo.setText("Compras dentro de un periodo");
        InventarioComprasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioComprasPeriodoActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioComprasPeriodo);

        ConsultasMenu.add(ConsultasInventarioMenu);

        menuBar.add(ConsultasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(AgregarProductoPanel);
    }//GEN-LAST:event_AgregarProductoGranelActionPerformed

    private void EliminarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(EliminarProductoPanel);
    }//GEN-LAST:event_EliminarProductoGranelActionPerformed

    private void ConsultarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(ConsultarProductoPanel);
    }//GEN-LAST:event_ConsultarProductoGranelActionPerformed

    private void ActualizarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(ActualizarProductoPanel);
    }//GEN-LAST:event_ActualizarProductoGranelActionPerformed

    private void AgregarProductoGranelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AgregarProductoGranelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoGranelComponentAdded

    private void MovimientosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosCompraActionPerformed
        // TODO add your handling code here:
        cambiarVista(MovimientosCompraPanel);
    }//GEN-LAST:event_MovimientosCompraActionPerformed

    private void MovimientosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosVentaActionPerformed
        // TODO add your handling code here:
        cambiarVista(MovimientosVentaPanel);
    }//GEN-LAST:event_MovimientosVentaActionPerformed

    private void AgregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(AgregarInventarioPanel);
    }//GEN-LAST:event_AgregarInventarioActionPerformed

    private void EliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(EliminarInventarioPanel);
    }//GEN-LAST:event_EliminarInventarioActionPerformed

    private void ActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(ActualizarInventarioPanel);
    }//GEN-LAST:event_ActualizarInventarioActionPerformed

    private void ProductoListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoCompletoActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoCompletoPanel);
    }//GEN-LAST:event_ProductoListadoCompletoActionPerformed

    private void ProductoListadoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoClaveActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoClavePanel);
    }//GEN-LAST:event_ProductoListadoClaveActionPerformed

    private void ProductoListadoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoTipoActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoTipoPanel);
    }//GEN-LAST:event_ProductoListadoTipoActionPerformed

    private void InventarioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioTodosActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioTodosPanel);
    }//GEN-LAST:event_InventarioTodosActionPerformed

    private void InventarioProductosGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioProductosGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioProductosGranelPanel);
    }//GEN-LAST:event_InventarioProductosGranelActionPerformed

    private void InventarioRegistroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioRegistroVentasActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioRegistroVentasPanel);
    }//GEN-LAST:event_InventarioRegistroVentasActionPerformed

    private void InventarioRegistroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioRegistroComprasActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioRegistroComprasPanel);
    }//GEN-LAST:event_InventarioRegistroComprasActionPerformed

    private void InventarioVentasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioVentasPeriodoActionPerformed
        // TODO add your handling code here:
        cambiarVista(RegistroVentasPeriodoPanel);
    }//GEN-LAST:event_InventarioVentasPeriodoActionPerformed

    private void InventarioComprasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioComprasPeriodoActionPerformed
        // TODO add your handling code here:
        cambiarVista(RegistroComprasPeriodoPanel);
    }//GEN-LAST:event_InventarioComprasPeriodoActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cambiarVista(JPanel jPanel){
        jPanel.setSize(JPanelPrincipal.getWidth(), JPanelPrincipal.getHeight());
        JPanelPrincipal.removeAll();
        JPanelPrincipal.add(jPanel);
        JPanelPrincipal.repaint();
        
        
        
    }
    
    private void activarVista(JPanel jPanel){
        AgregarProductoPanel.setEnabled(false);
        AgregarProductoPanel.setVisible(false);
        
        ConsultarProductoPanel.setEnabled(false);
        ConsultarProductoPanel.setVisible(false);
        
        ActualizarProductoPanel.setEnabled(false);
        ActualizarProductoPanel.setVisible(false);
        
        EliminarProductoPanel.setEnabled(false);
        EliminarProductoPanel.setVisible(false);
        
        MovimientosCompraPanel.setEnabled(false);
        MovimientosCompraPanel.setVisible(false);
        
        MovimientosVentaPanel.setEnabled(false);
        MovimientosVentaPanel.setVisible(false);
        
        AgregarInventarioPanel.setEnabled(false);
        AgregarInventarioPanel.setVisible(false);
        
        EliminarInventarioPanel.setEnabled(false);
        EliminarInventarioPanel.setVisible(false);
        
        ActualizarInventarioPanel.setEnabled(false);
        ActualizarInventarioPanel.setVisible(false);
        
        ListadoCompletoPanel.setEnabled(false);
        ListadoCompletoPanel.setVisible(false);
        
        ListadoClavePanel.setEnabled(false);
        ListadoClavePanel.setVisible(false);
        
        ListadoTipoPanel.setEnabled(false);
        ListadoTipoPanel.setVisible(false);
        
        InventarioTodosPanel.setEnabled(false);
        InventarioTodosPanel.setVisible(false);
        
        InventarioProductosGranelPanel.setEnabled(false);
        InventarioProductosGranelPanel.setVisible(false);
        
        InventarioRegistroVentasPanel.setEnabled(false);
        InventarioRegistroVentasPanel.setVisible(false);
        
        InventarioRegistroComprasPanel.setEnabled(false);
        InventarioRegistroComprasPanel.setVisible(false);
        
        RegistroVentasPeriodoPanel.setEnabled(false);
        RegistroVentasPeriodoPanel.setVisible(false);
        
        RegistroComprasPeriodoPanel.setEnabled(false);
        RegistroComprasPeriodoPanel.setVisible(false);
        
        jPanel.setEnabled(true);
        jPanel.setVisible(true);
        
    }
    
    public void ocultarTodo(){
        AgregarProductoPanel.setEnabled(false);
        AgregarProductoPanel.setVisible(false);
        
        ConsultarProductoPanel.setEnabled(false);
        ConsultarProductoPanel.setVisible(false);
        
        ActualizarProductoPanel.setEnabled(false);
        ActualizarProductoPanel.setVisible(false);
        
        EliminarProductoPanel.setEnabled(false);
        EliminarProductoPanel.setVisible(false);
        
        MovimientosCompraPanel.setEnabled(false);
        MovimientosCompraPanel.setVisible(false);
        
        MovimientosVentaPanel.setEnabled(false);
        MovimientosVentaPanel.setVisible(false);
        
        AgregarInventarioPanel.setEnabled(false);
        AgregarInventarioPanel.setVisible(false);
        
        EliminarInventarioPanel.setEnabled(false);
        EliminarInventarioPanel.setVisible(false);
        
        ActualizarInventarioPanel.setEnabled(false);
        ActualizarInventarioPanel.setVisible(false);
        
        ListadoCompletoPanel.setEnabled(false);
        ListadoCompletoPanel.setVisible(false);
        
        ListadoClavePanel.setEnabled(false);
        ListadoClavePanel.setVisible(false);
        
        ListadoTipoPanel.setEnabled(false);
        ListadoTipoPanel.setVisible(false);
        
        InventarioTodosPanel.setEnabled(false);
        InventarioTodosPanel.setVisible(false);
        
        InventarioProductosGranelPanel.setEnabled(false);
        InventarioProductosGranelPanel.setVisible(false);
        
        InventarioRegistroVentasPanel.setEnabled(false);
        InventarioRegistroVentasPanel.setVisible(false);
        
        InventarioRegistroComprasPanel.setEnabled(false);
        InventarioRegistroComprasPanel.setVisible(false);
        
        RegistroVentasPeriodoPanel.setEnabled(false);
        RegistroVentasPeriodoPanel.setVisible(false);
        
        RegistroComprasPeriodoPanel.setEnabled(false);
        RegistroComprasPeriodoPanel.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAbarrotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarInventario;
    private javax.swing.JPanel ActualizarInventarioPanel;
    private javax.swing.JMenuItem ActualizarProductoGranel;
    private javax.swing.JPanel ActualizarProductoPanel;
    private javax.swing.JMenuItem AgregarInventario;
    private javax.swing.JPanel AgregarInventarioPanel;
    private javax.swing.JMenuItem AgregarProductoGranel;
    private javax.swing.JPanel AgregarProductoPanel;
    private javax.swing.JMenu CatalogosMenu;
    private javax.swing.JMenuItem ConsultarProductoGranel;
    private javax.swing.JPanel ConsultarProductoPanel;
    private javax.swing.JMenu ConsultasInventarioMenu;
    private javax.swing.JMenu ConsultasMenu;
    private javax.swing.JMenu ConsultasProductoMenu;
    private javax.swing.JMenuItem EliminarInventario;
    private javax.swing.JPanel EliminarInventarioPanel;
    private javax.swing.JMenuItem EliminarProductoGranel;
    private javax.swing.JPanel EliminarProductoPanel;
    private javax.swing.JMenuItem InventarioComprasPeriodo;
    private javax.swing.JMenuItem InventarioProductosGranel;
    private javax.swing.JPanel InventarioProductosGranelPanel;
    private javax.swing.JMenuItem InventarioRegistroCompras;
    private javax.swing.JPanel InventarioRegistroComprasPanel;
    private javax.swing.JMenuItem InventarioRegistroVentas;
    private javax.swing.JPanel InventarioRegistroVentasPanel;
    private javax.swing.JMenuItem InventarioTodos;
    private javax.swing.JPanel InventarioTodosPanel;
    private javax.swing.JMenuItem InventarioVentasPeriodo;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JPanel ListadoClavePanel;
    private javax.swing.JPanel ListadoCompletoPanel;
    private javax.swing.JPanel ListadoTipoPanel;
    private javax.swing.JMenuItem MovimientosCompra;
    private javax.swing.JPanel MovimientosCompraPanel;
    private javax.swing.JMenu MovimientosInventarioMenu;
    private javax.swing.JMenu MovimientosMenu;
    private javax.swing.JMenuItem MovimientosVenta;
    private javax.swing.JPanel MovimientosVentaPanel;
    private javax.swing.JMenuItem ProductoListadoClave;
    private javax.swing.JMenuItem ProductoListadoCompleto;
    private javax.swing.JMenuItem ProductoListadoTipo;
    private javax.swing.JMenu ProductosGranelMenu;
    private javax.swing.JPanel RegistroComprasPeriodoPanel;
    private javax.swing.JPanel RegistroVentasPeriodoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
