/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package interfazUsuario;

import DAOs.MovimientosGranel;
import DAOs.ProductosGranel;
import PercistenciaListas.IPersistenciaFachada;
import PercistenciaListas.PersistenciaFachada;

import com.objetosnegocio.MovimientoGranel;
import com.objetosnegocio.Producto;
import com.objetosnegocio.ProductoGranel;
import com.objetosservicio.Fecha;
import com.objetosservicio.Periodo;

import javax.swing.JPanel;


/**
 *
 * @author joser
 */
public class FrmAbarrotes extends javax.swing.JFrame {
   
    
    
    Producto producto = new Producto("Papas Kiwi", "g", 'G');
    ProductoGranel productoG = new ProductoGranel(1f, producto);
    Producto producto2 = new Producto("Papas de fresa", "g", 'G');
    ProductoGranel productoG2 = new ProductoGranel(1f, producto);
    Producto producto3 = new Producto("Kiwi de sal", "g", 'G');
    ProductoGranel productoG3 = new ProductoGranel(1f, producto);
    
    

    /**
     * Creates new form FrmAbarrotes
     */
    public FrmAbarrotes() {
        initComponents();
        JPanelPrincipal.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        AgregarProductoPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        AgregarProductoNombre = new javax.swing.JTextField();
        AgregarProductoUnidad = new javax.swing.JTextField();
        AgregarProductoTipo = new javax.swing.JTextField();
        BotonAgregarProducto = new javax.swing.JButton();
        ConsultarProductoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ConsultarProductoId = new javax.swing.JTextField();
        BotonConsultarProducto = new javax.swing.JButton();
        ActualizarProductoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        IdProductoActualizar = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NuevoNombreActualizar = new javax.swing.JTextField();
        NuevaUnidadAcutalizar = new javax.swing.JTextField();
        NuevoTipoActualizar = new javax.swing.JTextField();
        BotonActualizarProducto = new javax.swing.JButton();
        EliminarProductoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IdProductoEliminar = new javax.swing.JTextField();
        BotonEliminarProducto = new javax.swing.JButton();
        MovimientoCompraPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        FechaMovimientoCompra = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        IdProductoMovimientoCompra = new javax.swing.JTextField();
        BotonActualizarProducto1 = new javax.swing.JButton();
        BooleanoMovimientoCompra = new javax.swing.JComboBox<>();
        MovimientoVentaPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        FechaMovimientoCompra1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        IdProductoMovimientoCompra1 = new javax.swing.JTextField();
        BotonActualizarProducto2 = new javax.swing.JButton();
        AgregarInventarioPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        EliminarInventarioPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ActualizarInventarioPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ListadoCompletoPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaProductos = new javax.swing.JList<>();
        ListadoCompletoBoton = new javax.swing.JButton();
        ListadoClavePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ListadoTipoPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        InventarioTodosPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        InventarioProductosGranelPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        InventarioRegistroVentasPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        InventarioRegistroComprasPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        RegistroVentasPeriodoPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        RegistroComprasPeriodoPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        CatalogosMenu = new javax.swing.JMenu();
        ProductosGranelMenu = new javax.swing.JMenu();
        AgregarProductoGranel = new javax.swing.JMenuItem();
        ConsultarProductoGranel = new javax.swing.JMenuItem();
        ActualizarProductoGranel = new javax.swing.JMenuItem();
        EliminarProductoGranel = new javax.swing.JMenuItem();
        MovimientosMenu = new javax.swing.JMenu();
        MovimientosCompra = new javax.swing.JMenuItem();
        MovimientosVenta = new javax.swing.JMenuItem();
        MovimientosInventarioMenu = new javax.swing.JMenu();
        AgregarInventario = new javax.swing.JMenuItem();
        EliminarInventario = new javax.swing.JMenuItem();
        ActualizarInventario = new javax.swing.JMenuItem();
        ConsultasMenu = new javax.swing.JMenu();
        ConsultasProductoMenu = new javax.swing.JMenu();
        ProductoListadoCompleto = new javax.swing.JMenuItem();
        ProductoListadoClave = new javax.swing.JMenuItem();
        ProductoListadoTipo = new javax.swing.JMenuItem();
        ConsultasInventarioMenu = new javax.swing.JMenu();
        InventarioTodos = new javax.swing.JMenuItem();
        InventarioProductosGranel = new javax.swing.JMenuItem();
        InventarioRegistroVentas = new javax.swing.JMenuItem();
        InventarioRegistroCompras = new javax.swing.JMenuItem();
        InventarioVentasPeriodo = new javax.swing.JMenuItem();
        InventarioComprasPeriodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("Nombre:");
        jLabel16.setPreferredSize(new java.awt.Dimension(140, 60));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setText("Unidad de medida:");
        jLabel20.setPreferredSize(new java.awt.Dimension(301, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Agregar Producto");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setText("Tipo:");
        jLabel21.setPreferredSize(new java.awt.Dimension(78, 60));

        AgregarProductoNombre.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AgregarProductoNombre.setPreferredSize(new java.awt.Dimension(147, 60));
        AgregarProductoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoNombreActionPerformed(evt);
            }
        });

        AgregarProductoUnidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AgregarProductoUnidad.setMinimumSize(new java.awt.Dimension(64, 60));
        AgregarProductoUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoUnidadActionPerformed(evt);
            }
        });

        AgregarProductoTipo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AgregarProductoTipo.setMinimumSize(new java.awt.Dimension(64, 60));
        AgregarProductoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoTipoActionPerformed(evt);
            }
        });

        BotonAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonAgregarProducto.setText("Enviar");
        BotonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarProductoPanelLayout = new javax.swing.GroupLayout(AgregarProductoPanel);
        AgregarProductoPanel.setLayout(AgregarProductoPanelLayout);
        AgregarProductoPanelLayout.setHorizontalGroup(
            AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarProductoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(AgregarProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarProductoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(BotonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AgregarProductoPanelLayout.setVerticalGroup(
            AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarProductoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarProductoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(BotonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Consultar Producto");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel22.setText("ID producto");
        jLabel22.setPreferredSize(new java.awt.Dimension(140, 60));

        ConsultarProductoId.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ConsultarProductoId.setPreferredSize(new java.awt.Dimension(147, 60));
        ConsultarProductoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarProductoIdActionPerformed(evt);
            }
        });

        BotonConsultarProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonConsultarProducto.setText("Enviar");
        BotonConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultarProductoPanelLayout = new javax.swing.GroupLayout(ConsultarProductoPanel);
        ConsultarProductoPanel.setLayout(ConsultarProductoPanelLayout);
        ConsultarProductoPanelLayout.setHorizontalGroup(
            ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(ConsultarProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                .addGroup(ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(BotonConsultarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConsultarProductoPanelLayout.setVerticalGroup(
            ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addGroup(ConsultarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultarProductoId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(BotonConsultarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        ActualizarProductoPanel.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Actualizar Producto");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setText("ID producto");
        jLabel23.setPreferredSize(new java.awt.Dimension(140, 60));

        IdProductoActualizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IdProductoActualizar.setPreferredSize(new java.awt.Dimension(147, 60));
        IdProductoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProductoActualizarActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel24.setText("Nuevo nombre");
        jLabel24.setPreferredSize(new java.awt.Dimension(140, 60));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel25.setText("Nueva unidad");
        jLabel25.setPreferredSize(new java.awt.Dimension(140, 60));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel26.setText("Nuevo tipo");
        jLabel26.setPreferredSize(new java.awt.Dimension(140, 60));

        NuevoNombreActualizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NuevoNombreActualizar.setPreferredSize(new java.awt.Dimension(147, 60));
        NuevoNombreActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoNombreActualizarActionPerformed(evt);
            }
        });

        NuevaUnidadAcutalizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NuevaUnidadAcutalizar.setPreferredSize(new java.awt.Dimension(147, 60));
        NuevaUnidadAcutalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaUnidadAcutalizarActionPerformed(evt);
            }
        });

        NuevoTipoActualizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NuevoTipoActualizar.setPreferredSize(new java.awt.Dimension(147, 60));
        NuevoTipoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoTipoActualizarActionPerformed(evt);
            }
        });

        BotonActualizarProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonActualizarProducto.setText("Enviar");
        BotonActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActualizarProductoPanelLayout = new javax.swing.GroupLayout(ActualizarProductoPanel);
        ActualizarProductoPanel.setLayout(ActualizarProductoPanelLayout);
        ActualizarProductoPanelLayout.setHorizontalGroup(
            ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(NuevoTipoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NuevaUnidadAcutalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NuevoNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdProductoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
            .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(BotonActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ActualizarProductoPanelLayout.setVerticalGroup(
            ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdProductoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NuevoNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NuevaUnidadAcutalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ActualizarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NuevoTipoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(BotonActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("Eliminar Producto");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel27.setText("ID producto");
        jLabel27.setPreferredSize(new java.awt.Dimension(140, 60));

        IdProductoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IdProductoEliminar.setPreferredSize(new java.awt.Dimension(147, 60));
        IdProductoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProductoEliminarActionPerformed(evt);
            }
        });

        BotonEliminarProducto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonEliminarProducto.setText("Enviar");
        BotonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarProductoPanelLayout = new javax.swing.GroupLayout(EliminarProductoPanel);
        EliminarProductoPanel.setLayout(EliminarProductoPanelLayout);
        EliminarProductoPanelLayout.setHorizontalGroup(
            EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarProductoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 436, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EliminarProductoPanelLayout.setVerticalGroup(
            EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarProductoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(EliminarProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(139, 139, 139)
                .addComponent(BotonEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        MovimientoCompraPanel.setPreferredSize(new java.awt.Dimension(900, 531));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("Realizar compra");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel28.setText("Fecha");
        jLabel28.setPreferredSize(new java.awt.Dimension(140, 60));

        FechaMovimientoCompra.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FechaMovimientoCompra.setPreferredSize(new java.awt.Dimension(147, 60));
        FechaMovimientoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaMovimientoCompraActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel29.setText("Procesado");
        jLabel29.setPreferredSize(new java.awt.Dimension(140, 60));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel30.setText("Id de producto gr.");
        jLabel30.setPreferredSize(new java.awt.Dimension(140, 60));

        IdProductoMovimientoCompra.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IdProductoMovimientoCompra.setPreferredSize(new java.awt.Dimension(147, 60));
        IdProductoMovimientoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProductoMovimientoCompraActionPerformed(evt);
            }
        });

        BotonActualizarProducto1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonActualizarProducto1.setText("Enviar");
        BotonActualizarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarProducto1ActionPerformed(evt);
            }
        });

        BooleanoMovimientoCompra.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BooleanoMovimientoCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        BooleanoMovimientoCompra.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                BooleanoMovimientoCompraComponentRemoved(evt);
            }
        });

        javax.swing.GroupLayout MovimientoCompraPanelLayout = new javax.swing.GroupLayout(MovimientoCompraPanel);
        MovimientoCompraPanel.setLayout(MovimientoCompraPanelLayout);
        MovimientoCompraPanelLayout.setHorizontalGroup(
            MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientoCompraPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MovimientoCompraPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MovimientoCompraPanelLayout.createSequentialGroup()
                        .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(244, 261, Short.MAX_VALUE)
                        .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdProductoMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BooleanoMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addContainerGap())
            .addGroup(MovimientoCompraPanelLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(BotonActualizarProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MovimientoCompraPanelLayout.setVerticalGroup(
            MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientoCompraPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(85, 85, 85)
                .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BooleanoMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MovimientoCompraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdProductoMovimientoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(BotonActualizarProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        MovimientoVentaPanel.setPreferredSize(new java.awt.Dimension(879, 526));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setText("Realizar Venta");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel31.setText("Fecha");
        jLabel31.setPreferredSize(new java.awt.Dimension(140, 60));

        FechaMovimientoCompra1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FechaMovimientoCompra1.setPreferredSize(new java.awt.Dimension(147, 60));
        FechaMovimientoCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaMovimientoCompra1ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel32.setText("Procesado");
        jLabel32.setPreferredSize(new java.awt.Dimension(140, 60));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        jComboBox2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jComboBox2ComponentRemoved(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel33.setText("Id de producto gr.");
        jLabel33.setPreferredSize(new java.awt.Dimension(140, 60));

        IdProductoMovimientoCompra1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        IdProductoMovimientoCompra1.setPreferredSize(new java.awt.Dimension(147, 60));
        IdProductoMovimientoCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProductoMovimientoCompra1ActionPerformed(evt);
            }
        });

        BotonActualizarProducto2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        BotonActualizarProducto2.setText("Enviar");
        BotonActualizarProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarProducto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MovimientoVentaPanelLayout = new javax.swing.GroupLayout(MovimientoVentaPanel);
        MovimientoVentaPanel.setLayout(MovimientoVentaPanelLayout);
        MovimientoVentaPanelLayout.setHorizontalGroup(
            MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(271, 271, 271)
                                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FechaMovimientoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IdProductoMovimientoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(BotonActualizarProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        MovimientoVentaPanelLayout.setVerticalGroup(
            MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovimientoVentaPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(85, 85, 85)
                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaMovimientoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MovimientoVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdProductoMovimientoCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(BotonActualizarProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setText("Agregar movimiento");

        javax.swing.GroupLayout AgregarInventarioPanelLayout = new javax.swing.GroupLayout(AgregarInventarioPanel);
        AgregarInventarioPanel.setLayout(AgregarInventarioPanelLayout);
        AgregarInventarioPanelLayout.setHorizontalGroup(
            AgregarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInventarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        AgregarInventarioPanelLayout.setVerticalGroup(
            AgregarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setText("Eliminar movimiento");

        javax.swing.GroupLayout EliminarInventarioPanelLayout = new javax.swing.GroupLayout(EliminarInventarioPanel);
        EliminarInventarioPanel.setLayout(EliminarInventarioPanelLayout);
        EliminarInventarioPanelLayout.setHorizontalGroup(
            EliminarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarInventarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        EliminarInventarioPanelLayout.setVerticalGroup(
            EliminarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setText("Actualizar movimiento");

        javax.swing.GroupLayout ActualizarInventarioPanelLayout = new javax.swing.GroupLayout(ActualizarInventarioPanel);
        ActualizarInventarioPanel.setLayout(ActualizarInventarioPanelLayout);
        ActualizarInventarioPanelLayout.setHorizontalGroup(
            ActualizarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );
        ActualizarInventarioPanelLayout.setVerticalGroup(
            ActualizarInventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarInventarioPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        ListadoCompletoPanel.setPreferredSize(new java.awt.Dimension(900, 453));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setText("Listado completo de productos");

        jScrollPane1.setViewportView(ListaProductos);

        ListadoCompletoBoton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ListadoCompletoBoton.setText("Enviar");
        ListadoCompletoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoCompletoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListadoCompletoPanelLayout = new javax.swing.GroupLayout(ListadoCompletoPanel);
        ListadoCompletoPanel.setLayout(ListadoCompletoPanelLayout);
        ListadoCompletoPanelLayout.setHorizontalGroup(
            ListadoCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                .addGroup(ListadoCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(ListadoCompletoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        ListadoCompletoPanelLayout.setVerticalGroup(
            ListadoCompletoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoCompletoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ListadoCompletoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel11.setText("Listado completo por clave");

        javax.swing.GroupLayout ListadoClavePanelLayout = new javax.swing.GroupLayout(ListadoClavePanel);
        ListadoClavePanel.setLayout(ListadoClavePanelLayout);
        ListadoClavePanelLayout.setHorizontalGroup(
            ListadoClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoClavePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        ListadoClavePanelLayout.setVerticalGroup(
            ListadoClavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoClavePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setText("Listado completo por tipo");

        javax.swing.GroupLayout ListadoTipoPanelLayout = new javax.swing.GroupLayout(ListadoTipoPanel);
        ListadoTipoPanel.setLayout(ListadoTipoPanelLayout);
        ListadoTipoPanelLayout.setHorizontalGroup(
            ListadoTipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoTipoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        ListadoTipoPanelLayout.setVerticalGroup(
            ListadoTipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoTipoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setText("Inventario");

        javax.swing.GroupLayout InventarioTodosPanelLayout = new javax.swing.GroupLayout(InventarioTodosPanel);
        InventarioTodosPanel.setLayout(InventarioTodosPanelLayout);
        InventarioTodosPanelLayout.setHorizontalGroup(
            InventarioTodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioTodosPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioTodosPanelLayout.setVerticalGroup(
            InventarioTodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioTodosPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setText("Inventario productos Granel");

        javax.swing.GroupLayout InventarioProductosGranelPanelLayout = new javax.swing.GroupLayout(InventarioProductosGranelPanel);
        InventarioProductosGranelPanel.setLayout(InventarioProductosGranelPanelLayout);
        InventarioProductosGranelPanelLayout.setHorizontalGroup(
            InventarioProductosGranelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioProductosGranelPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioProductosGranelPanelLayout.setVerticalGroup(
            InventarioProductosGranelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioProductosGranelPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setText("Registro de ventas");

        javax.swing.GroupLayout InventarioRegistroVentasPanelLayout = new javax.swing.GroupLayout(InventarioRegistroVentasPanel);
        InventarioRegistroVentasPanel.setLayout(InventarioRegistroVentasPanelLayout);
        InventarioRegistroVentasPanelLayout.setHorizontalGroup(
            InventarioRegistroVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroVentasPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioRegistroVentasPanelLayout.setVerticalGroup(
            InventarioRegistroVentasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroVentasPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel19.setText("Registro de compras");

        javax.swing.GroupLayout InventarioRegistroComprasPanelLayout = new javax.swing.GroupLayout(InventarioRegistroComprasPanel);
        InventarioRegistroComprasPanel.setLayout(InventarioRegistroComprasPanelLayout);
        InventarioRegistroComprasPanelLayout.setHorizontalGroup(
            InventarioRegistroComprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroComprasPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        InventarioRegistroComprasPanelLayout.setVerticalGroup(
            InventarioRegistroComprasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventarioRegistroComprasPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setText("Registro de ventas por periodo");

        javax.swing.GroupLayout RegistroVentasPeriodoPanelLayout = new javax.swing.GroupLayout(RegistroVentasPeriodoPanel);
        RegistroVentasPeriodoPanel.setLayout(RegistroVentasPeriodoPanelLayout);
        RegistroVentasPeriodoPanelLayout.setHorizontalGroup(
            RegistroVentasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroVentasPeriodoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        RegistroVentasPeriodoPanelLayout.setVerticalGroup(
            RegistroVentasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroVentasPeriodoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setText("Registro de compras por periodo");

        javax.swing.GroupLayout RegistroComprasPeriodoPanelLayout = new javax.swing.GroupLayout(RegistroComprasPeriodoPanel);
        RegistroComprasPeriodoPanel.setLayout(RegistroComprasPeriodoPanelLayout);
        RegistroComprasPeriodoPanelLayout.setHorizontalGroup(
            RegistroComprasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroComprasPeriodoPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        RegistroComprasPeriodoPanelLayout.setVerticalGroup(
            RegistroComprasPeriodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroComprasPeriodoPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel18)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MovimientoVentaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioProductosGranelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroVentasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroComprasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistroComprasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioTodosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoTipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoClavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoCompletoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MovimientoCompraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultarProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(RegistroVentasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MovimientoVentaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioProductosGranelPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroVentasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioRegistroComprasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RegistroComprasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InventarioTodosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoTipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoClavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ListadoCompletoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarInventarioPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MovimientoCompraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EliminarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ActualizarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ConsultarProductoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AgregarProductoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(RegistroVentasPeriodoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        CatalogosMenu.setMnemonic('c');
        CatalogosMenu.setText("Catalogos");

        ProductosGranelMenu.setText("Productos Granel");

        AgregarProductoGranel.setText("Agregar");
        AgregarProductoGranel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AgregarProductoGranelComponentAdded(evt);
            }
        });
        AgregarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(AgregarProductoGranel);

        ConsultarProductoGranel.setText("Consultar");
        ConsultarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(ConsultarProductoGranel);

        ActualizarProductoGranel.setText("Actualizar");
        ActualizarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(ActualizarProductoGranel);

        EliminarProductoGranel.setText("Eliminar");
        EliminarProductoGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoGranelActionPerformed(evt);
            }
        });
        ProductosGranelMenu.add(EliminarProductoGranel);

        CatalogosMenu.add(ProductosGranelMenu);

        menuBar.add(CatalogosMenu);

        MovimientosMenu.setMnemonic('m');
        MovimientosMenu.setText("Movimientos");

        MovimientosCompra.setText("Compra");
        MovimientosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosCompraActionPerformed(evt);
            }
        });
        MovimientosMenu.add(MovimientosCompra);

        MovimientosVenta.setText("Venta");
        MovimientosVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimientosVentaActionPerformed(evt);
            }
        });
        MovimientosMenu.add(MovimientosVenta);

        MovimientosInventarioMenu.setText("Inventario");

        AgregarInventario.setText("Agregar");
        AgregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(AgregarInventario);

        EliminarInventario.setText("Eliminar");
        EliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(EliminarInventario);

        ActualizarInventario.setText("Actualizar");
        ActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarInventarioActionPerformed(evt);
            }
        });
        MovimientosInventarioMenu.add(ActualizarInventario);

        MovimientosMenu.add(MovimientosInventarioMenu);

        menuBar.add(MovimientosMenu);

        ConsultasMenu.setMnemonic('x');
        ConsultasMenu.setText("Consultas");

        ConsultasProductoMenu.setText("Producto");

        ProductoListadoCompleto.setText("Listado completo");
        ProductoListadoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoCompletoActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoCompleto);

        ProductoListadoClave.setText("Listado por clave");
        ProductoListadoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoClaveActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoClave);

        ProductoListadoTipo.setText("Listado por tipo");
        ProductoListadoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoListadoTipoActionPerformed(evt);
            }
        });
        ConsultasProductoMenu.add(ProductoListadoTipo);

        ConsultasMenu.add(ConsultasProductoMenu);

        ConsultasInventarioMenu.setText("Inventario");

        InventarioTodos.setText("Todos los productos");
        InventarioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioTodosActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioTodos);

        InventarioProductosGranel.setText("Productos Granel");
        InventarioProductosGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioProductosGranelActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioProductosGranel);

        InventarioRegistroVentas.setText("Registro de ventas");
        InventarioRegistroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioRegistroVentasActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioRegistroVentas);

        InventarioRegistroCompras.setText("Registro de compras");
        InventarioRegistroCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioRegistroComprasActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioRegistroCompras);

        InventarioVentasPeriodo.setText("Ventas dentro de un periodo");
        InventarioVentasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioVentasPeriodoActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioVentasPeriodo);

        InventarioComprasPeriodo.setText("Compras dentro de un periodo");
        InventarioComprasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioComprasPeriodoActionPerformed(evt);
            }
        });
        ConsultasInventarioMenu.add(InventarioComprasPeriodo);

        ConsultasMenu.add(ConsultasInventarioMenu);

        menuBar.add(ConsultasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(AgregarProductoPanel);
        
    }//GEN-LAST:event_AgregarProductoGranelActionPerformed

    private void EliminarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(EliminarProductoPanel);
    }//GEN-LAST:event_EliminarProductoGranelActionPerformed

    private void ConsultarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(ConsultarProductoPanel);
    }//GEN-LAST:event_ConsultarProductoGranelActionPerformed

    private void ActualizarProductoGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(ActualizarProductoPanel);
    }//GEN-LAST:event_ActualizarProductoGranelActionPerformed

    private void AgregarProductoGranelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AgregarProductoGranelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoGranelComponentAdded

    private void MovimientosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosCompraActionPerformed
        // TODO add your handling code here:
        cambiarVista(MovimientoCompraPanel);
    }//GEN-LAST:event_MovimientosCompraActionPerformed

    private void MovimientosVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimientosVentaActionPerformed
        // TODO add your handling code here:
        cambiarVista(MovimientoVentaPanel);
    }//GEN-LAST:event_MovimientosVentaActionPerformed

    private void AgregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(AgregarInventarioPanel);
    }//GEN-LAST:event_AgregarInventarioActionPerformed

    private void EliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(EliminarInventarioPanel);
    }//GEN-LAST:event_EliminarInventarioActionPerformed

    private void ActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarInventarioActionPerformed
        // TODO add your handling code here:
        cambiarVista(ActualizarInventarioPanel);
    }//GEN-LAST:event_ActualizarInventarioActionPerformed

    private void ProductoListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoCompletoActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoCompletoPanel);
    }//GEN-LAST:event_ProductoListadoCompletoActionPerformed

    private void ProductoListadoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoClaveActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoClavePanel);
    }//GEN-LAST:event_ProductoListadoClaveActionPerformed

    private void ProductoListadoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoListadoTipoActionPerformed
        // TODO add your handling code here:
        cambiarVista(ListadoTipoPanel);
    }//GEN-LAST:event_ProductoListadoTipoActionPerformed

    private void InventarioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioTodosActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioTodosPanel);
    }//GEN-LAST:event_InventarioTodosActionPerformed

    private void InventarioProductosGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioProductosGranelActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioProductosGranelPanel);
    }//GEN-LAST:event_InventarioProductosGranelActionPerformed

    private void InventarioRegistroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioRegistroVentasActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioRegistroVentasPanel);
    }//GEN-LAST:event_InventarioRegistroVentasActionPerformed

    private void InventarioRegistroComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioRegistroComprasActionPerformed
        // TODO add your handling code here:
        cambiarVista(InventarioRegistroComprasPanel);
    }//GEN-LAST:event_InventarioRegistroComprasActionPerformed

    private void InventarioVentasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioVentasPeriodoActionPerformed
        // TODO add your handling code here:
        cambiarVista(RegistroVentasPeriodoPanel);
    }//GEN-LAST:event_InventarioVentasPeriodoActionPerformed

    private void InventarioComprasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioComprasPeriodoActionPerformed
        // TODO add your handling code here:
        cambiarVista(RegistroComprasPeriodoPanel);
    }//GEN-LAST:event_InventarioComprasPeriodoActionPerformed

    private void AgregarProductoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoNombreActionPerformed

    private void AgregarProductoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoTipoActionPerformed

    private void AgregarProductoUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductoUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarProductoUnidadActionPerformed

    private void ConsultarProductoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarProductoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarProductoIdActionPerformed

    private void IdProductoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProductoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProductoActualizarActionPerformed

    private void NuevoNombreActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoNombreActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoNombreActualizarActionPerformed

    private void NuevaUnidadAcutalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaUnidadAcutalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaUnidadAcutalizarActionPerformed

    private void NuevoTipoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoTipoActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoTipoActualizarActionPerformed

    private void BotonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAgregarProductoActionPerformed

    private void BotonConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonConsultarProductoActionPerformed

    private void BotonActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarProductoActionPerformed

    private void IdProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProductoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProductoEliminarActionPerformed

    private void BotonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarProductoActionPerformed

    private void FechaMovimientoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaMovimientoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaMovimientoCompraActionPerformed

    private void IdProductoMovimientoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProductoMovimientoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProductoMovimientoCompraActionPerformed

    private void BotonActualizarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarProducto1ActionPerformed

    private void FechaMovimientoCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaMovimientoCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaMovimientoCompra1ActionPerformed

    private void jComboBox2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBox2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ComponentRemoved

    private void IdProductoMovimientoCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProductoMovimientoCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProductoMovimientoCompra1ActionPerformed

    private void BotonActualizarProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarProducto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonActualizarProducto2ActionPerformed

    private void BooleanoMovimientoCompraComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_BooleanoMovimientoCompraComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_BooleanoMovimientoCompraComponentRemoved

    private void ListadoCompletoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoCompletoBotonActionPerformed
        // TODO add your handling code here:
        //Mostrar Lista de elementos producto
        
    }//GEN-LAST:event_ListadoCompletoBotonActionPerformed

    private void cambiarVista(JPanel jPanel){
        jPanel.setSize(JPanelPrincipal.getWidth(), JPanelPrincipal.getHeight());
        JPanelPrincipal.removeAll();
        JPanelPrincipal.repaint();
        JPanelPrincipal.add(jPanel);
        JPanelPrincipal.repaint();

        
        
    }
    
    private void activarVista(JPanel jPanel){
        AgregarProductoPanel.setEnabled(false);
        AgregarProductoPanel.setVisible(false);
        
        ConsultarProductoPanel.setEnabled(false);
        ConsultarProductoPanel.setVisible(false);
        
        ActualizarProductoPanel.setEnabled(false);
        ActualizarProductoPanel.setVisible(false);
        
        EliminarProductoPanel.setEnabled(false);
        EliminarProductoPanel.setVisible(false);
        
        MovimientoCompraPanel.setEnabled(false);
        MovimientoCompraPanel.setVisible(false);
        
        MovimientoVentaPanel.setEnabled(false);
        MovimientoVentaPanel.setVisible(false);
        
        AgregarInventarioPanel.setEnabled(false);
        AgregarInventarioPanel.setVisible(false);
        
        EliminarInventarioPanel.setEnabled(false);
        EliminarInventarioPanel.setVisible(false);
        
        ActualizarInventarioPanel.setEnabled(false);
        ActualizarInventarioPanel.setVisible(false);
        
        ListadoCompletoPanel.setEnabled(false);
        ListadoCompletoPanel.setVisible(false);
        
        ListadoClavePanel.setEnabled(false);
        ListadoClavePanel.setVisible(false);
        
        ListadoTipoPanel.setEnabled(false);
        ListadoTipoPanel.setVisible(false);
        
        InventarioTodosPanel.setEnabled(false);
        InventarioTodosPanel.setVisible(false);
        
        InventarioProductosGranelPanel.setEnabled(false);
        InventarioProductosGranelPanel.setVisible(false);
        
        InventarioRegistroVentasPanel.setEnabled(false);
        InventarioRegistroVentasPanel.setVisible(false);
        
        InventarioRegistroComprasPanel.setEnabled(false);
        InventarioRegistroComprasPanel.setVisible(false);
        
        RegistroVentasPeriodoPanel.setEnabled(false);
        RegistroVentasPeriodoPanel.setVisible(false);
        
        RegistroComprasPeriodoPanel.setEnabled(false);
        RegistroComprasPeriodoPanel.setVisible(false);
        
        jPanel.setEnabled(true);
        jPanel.setVisible(true);
        
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAbarrotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarInventario;
    private javax.swing.JPanel ActualizarInventarioPanel;
    private javax.swing.JMenuItem ActualizarProductoGranel;
    private javax.swing.JPanel ActualizarProductoPanel;
    private javax.swing.JMenuItem AgregarInventario;
    private javax.swing.JPanel AgregarInventarioPanel;
    private javax.swing.JMenuItem AgregarProductoGranel;
    private javax.swing.JTextField AgregarProductoNombre;
    private javax.swing.JPanel AgregarProductoPanel;
    private javax.swing.JTextField AgregarProductoTipo;
    private javax.swing.JTextField AgregarProductoUnidad;
    private javax.swing.JComboBox<String> BooleanoMovimientoCompra;
    private javax.swing.JButton BotonActualizarProducto;
    private javax.swing.JButton BotonActualizarProducto1;
    private javax.swing.JButton BotonActualizarProducto2;
    private javax.swing.JButton BotonAgregarProducto;
    private javax.swing.JButton BotonConsultarProducto;
    private javax.swing.JButton BotonEliminarProducto;
    private javax.swing.JMenu CatalogosMenu;
    private javax.swing.JMenuItem ConsultarProductoGranel;
    private javax.swing.JTextField ConsultarProductoId;
    private javax.swing.JPanel ConsultarProductoPanel;
    private javax.swing.JMenu ConsultasInventarioMenu;
    private javax.swing.JMenu ConsultasMenu;
    private javax.swing.JMenu ConsultasProductoMenu;
    private javax.swing.JMenuItem EliminarInventario;
    private javax.swing.JPanel EliminarInventarioPanel;
    private javax.swing.JMenuItem EliminarProductoGranel;
    private javax.swing.JPanel EliminarProductoPanel;
    private javax.swing.JTextField FechaMovimientoCompra;
    private javax.swing.JTextField FechaMovimientoCompra1;
    private javax.swing.JTextField IdProductoActualizar;
    private javax.swing.JTextField IdProductoEliminar;
    private javax.swing.JTextField IdProductoMovimientoCompra;
    private javax.swing.JTextField IdProductoMovimientoCompra1;
    private javax.swing.JMenuItem InventarioComprasPeriodo;
    private javax.swing.JMenuItem InventarioProductosGranel;
    private javax.swing.JPanel InventarioProductosGranelPanel;
    private javax.swing.JMenuItem InventarioRegistroCompras;
    private javax.swing.JPanel InventarioRegistroComprasPanel;
    private javax.swing.JMenuItem InventarioRegistroVentas;
    private javax.swing.JPanel InventarioRegistroVentasPanel;
    private javax.swing.JMenuItem InventarioTodos;
    private javax.swing.JPanel InventarioTodosPanel;
    private javax.swing.JMenuItem InventarioVentasPeriodo;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JList<String> ListaProductos;
    private javax.swing.JPanel ListadoClavePanel;
    private javax.swing.JButton ListadoCompletoBoton;
    private javax.swing.JPanel ListadoCompletoPanel;
    private javax.swing.JPanel ListadoTipoPanel;
    private javax.swing.JPanel MovimientoCompraPanel;
    private javax.swing.JPanel MovimientoVentaPanel;
    private javax.swing.JMenuItem MovimientosCompra;
    private javax.swing.JMenu MovimientosInventarioMenu;
    private javax.swing.JMenu MovimientosMenu;
    private javax.swing.JMenuItem MovimientosVenta;
    private javax.swing.JTextField NuevaUnidadAcutalizar;
    private javax.swing.JTextField NuevoNombreActualizar;
    private javax.swing.JTextField NuevoTipoActualizar;
    private javax.swing.JMenuItem ProductoListadoClave;
    private javax.swing.JMenuItem ProductoListadoCompleto;
    private javax.swing.JMenuItem ProductoListadoTipo;
    private javax.swing.JMenu ProductosGranelMenu;
    private javax.swing.JPanel RegistroComprasPeriodoPanel;
    private javax.swing.JPanel RegistroVentasPeriodoPanel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
